INSERT INTO categories (name) VALUES 
('Accesorios para Vehículos'),
('Acc. para Motos y Cuatriciclos'),
('Acc. y Repuestos Náuticos'),
('Accesorios de Auto y Camioneta'),
('Accesorios para Camiones'),
('Audio para Vehículos'),
('Dispositivos para TelePASE'),
('GNC'),
('Herramientas'),
('Limpieza de Vehículos'),
('Llantas'),
('Navegadores GPS'),
('Neumáticos'),
('Performance'),
('Repuestos Autos y Camionetas'),
('Repuestos de Línea Pesada'),
('Repuestos Motos y Cuatriciclos'),
('Seguridad Vehicular'),
('Servicio Programado'),
('Tuning'),
('Otros'),
('Agro'),
('Animales'),
('Generadores de Energía'),
('Infraestructura Rural'),
('Insumos Agrícolas'),
('Insumos Ganaderos'),
('Máquinas y Herramientas'),
('Repuestos Maquinaria Agrícola'),
('Otros'),
('Alimentos y Bebidas'),
('Bebidas'),
('Comestibles'),
('Comida Preparada y Catering'),
('Congelados'),
('Frescos'),
('Otros'),
('Animales y Mascotas'),
('Aves'),
('Caballos'),
('Conejos'),
('Gatos'),
('Insectos'),
('Peces'),
('Perros'),
('Reptiles y Anfibios'),
('Roedores'),
('Otros'),
('Antigüedades y Colecciones'),
('Antigüedades'),
('Coleccionables de Deportes'),
('Esculturas'),
('Filatelia'),
('Militaría y Afines'),
('Monedas y Billetes'),
('Posters'),
('Otros'),
('Arte, Librería y Mercería'),
('Arte'),
('Espejos Venecitas'),
('Insumos para Hacer Velas'),
('Librería'),
('Mercería'),
('Moldes para Jabones'),
('Piezas para Llaveros'),
('Otros'),
('Autos, Motos y Otros'),
('Autos Chocados y Averiados'),
('Autos de Colección'),
('Autos y Camionetas'),
('Camiones'),
('Colectivos'),
('Maquinaria Agrícola'),
('Maquinaria Vial'),
('Motorhomes'),
('Motos'),
('Náutica'),
('Planes de Ahorro'),
('Semirremolques'),
('Otros Vehículos'),
('Bebés'),
('Andadores y Vehículos de Bebés'),
('Artículos de Bebés para Baño'),
('Artículos de Maternidad'),
('Chupetes y Mordillos'),
('Comida para Bebés'),
('Corralitos'),
('Cuarto del Bebé'),
('Higiene y Cuidado del Bebé'),
('Juegos y Juguetes para Bebés'),
('Lactancia y Alimentación'),
('Paseo del Bebé'),
('Ropa y Calzado para Bebés'),
('Salud del Bebé'),
('Seguridad para Bebés'),
('Otros'),
('Belleza y Cuidado Personal'),
('Artículos de Peluquería'),
('Barbería'),
('Cuidado de la Piel'),
('Cuidado del Cabello'),
('Depilación'),
('Electrodomésticos de Belleza'),
('Farmacia'),
('Higiene Personal'),
('Manicuría y Pedicuría'),
('Maquillaje'),
('Perfumes y Fragancias'),
('Tratamientos de Belleza'),
('Otros'),
('Cámaras y Accesorios'),
('Accesorios para Cámaras'),
('Álbumes y Portarretratos'),
('Cables'),
('Cámaras'),
('Drones y Accesorios'),
('Filmadoras y Cámaras de Acción'),
('Instrumentos Ópticos'),
('Lentes y Filtros'),
('Repuestos para Cámaras'),
('Revelado y Laboratorio'),
('Otros'),
('Celulares y Teléfonos'),
('Accesorios para Celulares'),
('Celulares y Smartphones'),
('Handies y Radiofrecuencia'),
('Lentes de Realidad Virtual'),
('Repuestos de Celulares'),
('Smartwatches y Accesorios'),
('Tarifadores y Cabinas'),
('Telefonía Fija e Inalámbrica'),
('Telefonía IP'),
('Otros'),
('Computación'),
('Accesorios de Antiestática'),
('Accesorios para PC Gaming'),
('Almacenamiento'),
('Cables y Hubs USB'),
('Cajas, Sobres y Porta CDs'),
('Componentes de PC'),
('Conectividad y Redes'),
('Estabilizadores y UPS'),
('Impresión'),
('Laptops y Accesorios'),
('Lectores y Scanners'),
('Limpieza y Cuidado de PCs'),
('Monitores y Accesorios'),
('Palms y Handhelds'),
('PC de Escritorio'),
('Periféricos de PC'),
('Proyectores y Pantallas'),
('Software'),
('Tablets y Accesorios'),
('Otros'),
('Consolas y Videojuegos'),
('Accesorios para Consolas'),
('Accesorios para PC Gaming'),
('Consolas'),
('Flippers y Arcade'),
('Repuestos para Consolas'),
('Videojuegos'),
('Otros'),
('Deportes y Fitness'),
('Artes Marciales y Boxeo'),
('Bádminton'),
('Básquet'),
('Buceo'),
('Camping, Caza y Pesca'),
('Canoas, Kayaks e Inflables'),
('Ciclismo'),
('Equitación y Polo'),
('Esgrima'),
('Esqui y Snowboard'),
('Fitness y Musculación'),
('Fútbol'),
('Fútbol Americano'),
('Golf'),
('Handball'),
('Hockey'),
('Juegos de Salón'),
('Kitesurf'),
('Monopatines y Scooters'),
('Montañismo y Trekking'),
('Natación'),
('Paintball'),
('Parapente'),
('Patín, Gimnasia y Danza'),
('Pilates y Yoga'),
('Pulsómetros y Cronómetros'),
('Ropa Deportiva'),
('Rugby'),
('Skateboard y Sandboard'),
('Slackline'),
('Softball y Beisbol'),
('Suplementos y Shakers'),
('Surf y Bodyboard'),
('Tenis, Padel y Squash'),
('Tiro Deportivo'),
('Voley'),
('Wakeboard y Esqui Acuático'),
('Windsurf'),
('Zapatillas'),
('Otros'),
('Electrodomésticos y Aires Ac.'),
('Artefactos de Cuidado Personal'),
('Climatización'),
('Cocción'),
('Dispensadores y Purificadores'),
('Lavado'),
('Pequeños Electrodomésticos'),
('Refrigeración'),
('Otros'),
('Electrónica, Audio y Video'),
('Accesorios para Audio y Video'),
('Accesorios para TV'),
('Audio'),
('Cables'),
('Componentes Electrónicos'),
('Controles Remotos'),
('Drones y Accesorios'),
('Fundas y Bolsos'),
('Media Streaming'),
('Pilas y Cargadores'),
('Proyectores y Pantallas'),
('Repuestos para TV'),
('Televisores'),
('Video'),
('Otros'),
('Entradas para Eventos'),
('Entradas de Colección'),
('Eventos a Beneficio'),
('Eventos Deportivos'),
('Exposiciones'),
('Recitales'),
('Teatro'),
('Otras Entradas'),
('Herramientas y Construcción'),
('Aberturas'),
('Baños y Sanitarios'),
('Construcción'),
('Electricidad'),
('Herramientas'),
('Mobiliario para Cocinas'),
('Pinturería'),
('Pisos y Revestimientos'),
('Plomería'),
('Otros'),
('Hogar, Muebles y Jardín'),
('Adornos y Decoración del Hogar'),
('Baños'),
('Bazar y Cocina'),
('Camas, Colchones y Accesorios'),
('Cuidado del Hogar y Lavandería'),
('Iluminación para el Hogar'),
('Jardin y Aire Libre'),
('Muebles para el Hogar'),
('Organización para el Hogar'),
('Seguridad para el Hogar'),
('Textiles de Hogar y Decoración'),
('Otros'),
('Industrias y Oficinas'),
('Arquitectura y Diseño'),
('Embalaje y Logística'),
('Equipamiento Médico'),
('Equipamiento para Comercios'),
('Equipamiento para Oficinas'),
('Gastronomía y Hotelería'),
('Gráfica e Impresión'),
('Herramientas Industriales'),
('Publicidad y Promoción'),
('Seguridad Laboral'),
('Textil y Calzado'),
('Uniformes'),
('Otros'),
('Inmuebles'),
('Camas Náuticas'),
('Campos'),
('Casas'),
('Cocheras'),
('Consultorios'),
('Departamentos'),
('Depósitos y Galpones'),
('Fondo de Comercio'),
('Locales'),
('Oficinas'),
('Parcelas, Nichos y Bóvedas'),
('PH'),
('Quintas'),
('Terrenos y Lotes'),
('Tiempo Compartido'),
('Otros Inmuebles'),
('Instrumentos Musicales'),
('Baterías y Percusión'),
('Equipos de DJ y Accesorios'),
('Estudio de Grabación'),
('Instrumentos de Cuerdas'),
('Instrumentos de Viento'),
('Metrónomos'),
('Micrófonos y Amplificadores'),
('Parlantes y Bafles'),
('Partituras y Letras'),
('Pedales y Accesorios'),
('Teclados y Pianos'),
('Otros'),
('Joyas y Relojes'),
('Exhibidores y Joyeros'),
('Insumos para Joyería'),
('Joyas y Bijouterie'),
('Piedras Preciosas'),
('Piercings'),
('Plumas y Lapiceras de Lujo'),
('Pulsómetros y Cronómetros'),
('Relojes'),
('Repuestos para Relojes'),
('Smartwatch'),
('Otros'),
('Juegos y Juguetes'),
('Armas y Lanzadores de Juguete'),
('Casas y Carpas para Niños'),
('Dibujo, Pintura y Manualidades'),
('Electrónicos para Niños'),
('Figuritas, Álbumes y Cromos'),
('Hobbies'),
('Instrumentos Musicales'),
('Juegos de Agua y Playa'),
('Juegos de Mesa y Cartas'),
('Juegos de Plaza y Aire Libre'),
('Juegos de Salón'),
('Juguetes Antiestrés e Ingenio'),
('Juguetes de Bromas'),
('Juguetes de Construcción'),
('Juguetes de Oficios'),
('Juguetes para Bebés'),
('Mesas y Sillas para Niños'),
('Muñecos y Muñecas'),
('Patines y Patinetas'),
('Peloteros y Castillos'),
('Peluches'),
('Títeres y Marionetas'),
('Vehículos de Juguete'),
('Vehículos Montables para Niños'),
('Otros'),
('Libros, Revistas y Comics'),
('Catálogos'),
('Comics e Historietas'),
('Libros'),
('Manga'),
('Revistas'),
('Otros'),
('Música, Películas y Series'),
('Cursos'),
('Música'),
('Películas'),
('Series de TV'),
('Otros'),
('Ropa y Accesorios'),
('Accesorios de Moda'),
('Bermudas y Shorts'),
('Blusas'),
('Buzos y Hoodies'),
('Calzado'),
('Calzas'),
('Camisas'),
('Camperas, Tapados y Trenchs'),
('Enteritos'),
('Equipaje, Bolsos y Carteras'),
('Lotes de Ropa'),
('Pantalones, Jeans y Joggings'),
('Polleras'),
('Remeras, Musculosas y Chombas'),
('Ropa de Danza y Patinaje'),
('Ropa Deportiva'),
('Ropa Interior y de Dormir'),
('Ropa y Calzado para Bebés'),
('Saquitos, Sweaters y Chalecos'),
('Trajes'),
('Trajes de Baño'),
('Uniformes y Ropa de Trabajo'),
('Vestidos'),
('Otros'),
('Salud y Equipamiento Médico'),
('Cuidado de la Salud'),
('Equipamiento Médico'),
('Masajes'),
('Movilidad'),
('Ortopedia'),
('Suplementos Alimenticios'),
('Terapias Alternativas'),
('Otros'),
('Servicios'),
('Asesoramiento Contable y Legal'),
('Belleza y Cuidado Personal'),
('Comunicación y diseño'),
('Cursos y Clases'),
('Delivery'),
('Fiestas y Eventos'),
('Fotografía, Música y Cine'),
('Hogar y Construcción'),
('Imprenta'),
('Mantenimiento de Vehículos'),
('Medicina y Salud'),
('Ropa y Moda'),
('Servicios para Mascotas'),
('Servicios para Oficinas'),
('Tecnología'),
('Transporte'),
('Viajes y Turismo'),
('Otros Servicios'),
('Souvenirs, Cotillón y Fiestas'),
('Cotillón'),
('Decoración para Fiestas'),
('Descartables para Fiestas'),
('Disfraces'),
('Espuma, Serpentina y Confeti'),
('Invitaciones y Tarjetas'),
('Kits Imprimibles para Fiestas'),
('Props para Photo Booths'),
('Souvenirs'),
('Otros'),
('Otras categorías'),
('Adultos'),
('Artículos para Fumadores'),
('Coberturas Extendidas'),
('Criptomonedas'),
('Esoterismo'),
('Gift Cards'),
('Hornos Crematorios'),
('Insumos para Tatuajes'),
('Kits de Criminalística'),
('Licencias para Taxis'),
('Mangas de Viento'),
('Pirotecnia'),
('Otros');



INSERT INTO brands (name) VALUES 
('Apple'),
('Amazon'),
('Google'),
('Microsoft'),
('Samsung Group'),
('Walmart'),
('Facebook'),
('ICBC'),
('Verizon'),
('WeChat'),
('China Construction Bank'),
('Toyota'),
('Mercedes-Benz'),
('Tencent'),
('Huawei'),
('State Grid'),
('Ping An'),
('Taobao'),
('Agricultural Bank Of China'),
('Home Depot'),
('AT&amp;T'),
('Disney'),
('Deutsche Telekom'),
('Tmall'),
('Bank of China'),
('Volkswagen'),
('Moutai'),
('Shell'),
('BMW'),
('Alibaba.com'),
('Starbucks'),
('China Mobile'),
('Saudi Aramco'),
('Mitsubishi Group'),
('Marlboro'),
('Porsche'),
('NTT Group'),
('McDonald\'s'),
('Coca-Cola'),
('Bank of America'),
('Citi'),
('Tesla'),
('Intel'),
('Wells Fargo'),
('PetroChina'),
('Honda'),
('Nike'),
('CSCEC'),
('Lowe\'s'),
('UPS'),
('Costco'),
('Chase'),
('IBM'),
('UnitedHealthcare'),
('CVS'),
('Deloitte'),
('VISA'),
('Sinopec'),
('Oracle'),
('accenture'),
('Wuliangye'),
('Xfinity'),
('Instagram'),
('Netflix'),
('Sumitomo Group'),
('JP Morgan'),
('American Express'),
('JD.com'),
('FedEx'),
('Hyundai Group'),
('Ford'),
('China Life'),
('Mitsui'),
('PWC'),
('Spectrum'),
('BP'),
('TATA Group'),
('SK Group'),
('China Merchants Bank'),
('Target'),
('Siemens Group'),
('Uber'),
('EY'),
('Allianz'),
('Evergrande'),
('Cisco'),
('Country Garden'),
('Nestle'),
('Vodafone'),
('Mastercard'),
('Orange'),
('LG Group'),
('Dell Technologies'),
('Bosch'),
('Pepsi'),
('Total'),
('General Electric'),
('SAP'),
('IKEA'),
('Volvo'),
('Axa'),
('YouTube'),
('Audi'),
('Vanke'),
('HSBC'),
('PayPal'),
('Nissan'),
('Walgreens'),
('Hitachi'),
('TD'),
('Chevron'),
('CRCC'),
('Anthem'),
('RBC'),
('Sony'),
('Bank of Communications'),
('GUCCI'),
('Aldi'),
('CPIC'),
('KFC'),
('Shanghai Pudong Development Bank'),
('CRECG'),
('Louis Vuitton'),
('au'),
('China CITIC Bank'),
('Adidas'),
('Santander'),
('AIA'),
('NetEase'),
('Goldman Sachs'),
('Chevrolet'),
('Boeing'),
('Postal Savings Bank'),
('ExxonMobil'),
('Humana'),
('China Telecom'),
('Chanel'),
('Salesforce'),
('ZARA'),
('UNIQLO'),
('Capital One'),
('SoftBank'),
('China Minsheng Bank'),
('Optum'),
('BNP Paribas'),
('H&amp;M'),
('TSMC'),
('KPMG'),
('MUFG'),
('Industrial Bank'),
('Cartier'),
('Petronas'),
('Enel'),
('JR'),
('Adobe'),
('Hermès'),
('Universal'),
('Lidl'),
('Greenland'),
('Longfor Properties'),
('GEICO'),
('Sam\'s Club'),
('ADNOC'),
('Johnson &amp; Johnson'),
('Lockheed Martin'),
('China Everbright Bank'),
('L\'Oréal'),
('Warner Bros'),
('Tesco'),
('ING'),
('Renault'),
('Sephora'),
('Panasonic'),
('Midea'),
('China Resources Land'),
('Dollar General'),
('Yili'),
('DHL'),
('Morgan Stanley'),
('Sber'),
('Nokia'),
('ENGIE'),
('Yahoo! Group'),
('Xiaomi'),
('Medtronic'),
('China Overseas Land &amp; Invest'),
('EDF'),
('Ferrari'),
('STC'),
('Purina'),
('Airbus'),
('7-Eleven'),
('Poly Real Estate'),
('BMO'),
('Scotiabank'),
('Barclays'),
('Sky'),
('Woolworths'),
('Progressive'),
('Equinor'),
('Lexus'),
('PICC'),
('Japan Post Holdings'),
('S&amp;P Global'),
('UBS'),
('LIC'),
('Gree'),
('Etisalat'),
('Eni'),
('NBC'),
('HP'),
('Infosys'),
('U.S. Bank'),
('eBay'),
('Metlife'),
('Brookfield'),
('Power China'),
('LinkedIn'),
('E.Leclerc'),
('booking.com'),
('Canon'),
('Danone'),
('Carrefour'),
('Subway'),
('Subaru'),
('Red Bull'),
('Reliance'),
('ESPN'),
('Nvidia'),
('Publix'),
('Cognizant'),
('Truist'),
('3M'),
('HCA'),
('Vinci'),
('Travelers'),
('Rolex'),
('China Unicom'),
('Caterpillar'),
('John Deere'),
('Movistar'),
('Dior'),
('Haier'),
('DBS'),
('Baidu'),
('Rakuten'),
('Zurich'),
('Roche'),
('Marubeni'),
('BBVA'),
('Fox'),
('BNSF'),
('Hilton'),
('Generali Group'),
('Rabobank'),
('Gillette'),
('Union Pacific'),
('Philips'),
('Sunac'),
('Intesa Sanpaolo'),
('BASF'),
('Chubb'),
('Bell'),
('Merrill'),
('Meituan'),
('Canada Life'),
('Pall Mall'),
('Yanghe'),
('CNBM'),
('SF Express'),
('Luzhou Laojiao'),
('Northrop Grumman'),
('Cigna'),
('Telenor'),
('CIBC'),
('Land Rover'),
('L&amp;M'),
('Allstate'),
('Michelin'),
('VMWARE'),
('Aviva'),
('Telstra'),
('Nippon Life Insurance'),
('Sherwin-Williams'),
('Bridgestone'),
('PNC'),
('CNOOC'),
('Pampers'),
('CRRC'),
('Capgemini'),
('Playstation'),
('Enterprise'),
('Kellogg\'s'),
('3'),
('HDFC Bank'),
('Aetna'),
('Lay\'s'),
('Commonwealth Bank'),
('Broadcom'),
('TJ Maxx'),
('Asda'),
('Mizuho Financial Group'),
('Kroger'),
('Gazprom'),
('Daiwa House'),
('Honeywell'),
('Activision Blizzard'),
('Tyson'),
('MCC'),
('Credit Suisse'),
('Telus'),
('Thermo Fisher Scientific'),
('Best Buy'),
('Youku'),
('Raytheon Technologies'),
('Poste Italiane'),
('Nivea'),
('Fubon Financial'),
('Hikvision'),
('El Corte Inglés'),
('QNB'),
('Domino\'s Pizza'),
('Airtel'),
('20th Television'),
('Viettel'),
('Standard Chartered'),
('TIM'),
('KEPCO'),
('Nescafé'),
('Bouygues'),
('Circle K'),
('CBS'),
('ABC'),
('State Bank of India'),
('Corona'),
('Qualcomm'),
('Taco Bell'),
('Delta'),
('BT'),
('Valero'),
('Dunkin'),
('Guerlain'),
('Estée Lauder'),
('Heineken'),
('FIS'),
('AutoZone'),
('Coles'),
('HPE'),
('BAE Systems'),
('Spotify'),
('Discover'),
('Pemex'),
('HCL'),
('Fresenius'),
('O2'),
('Jeep'),
('Nintendo'),
('China Post'),
('Xbox'),
('Lukoil'),
('Whole Foods'),
('Tiffany &amp; Co.'),
('CFLD'),
('SFR'),
('CJ Group'),
('Lego'),
('Unicharm Corp'),
('Mahindra Group'),
('Munich Re'),
('Suning'),
('Tokio Marine'),
('American Airlines'),
('Lenovo'),
('CCCC'),
('Chow Tai Fook'),
('Swisscom'),
('PTT'),
('Pantene'),
('Kia'),
('McKinsey'),
('Carmax'),
('Iberdrola'),
('Pizza Hut'),
('Manulife'),
('Dove'),
('Société Générale'),
('Banco Itaú'),
('Hua Xia Bank'),
('Crédit Mutuel'),
('ADP'),
('Wrigley'),
('Shinhan Financial Group'),
('Sysco'),
('General Dynamics'),
('Clinique'),
('United Airlines'),
('Prudential (US)'),
('BHP'),
('AbbVie'),
('Applied Materials'),
('McKesson'),
('Lloyds Bank'),
('Centene Corporation'),
('Swiss Re'),
('Monster'),
('Crédit Agricole'),
('NatWest'),
('Jio'),
('Budweiser'),
('Mengniu'),
('Mercadona'),
('Centurylink'),
('E.ON'),
('ABB'),
('Zalando'),
('COACH'),
('Micron Technology'),
('Hyatt'),
('KB Financial Group'),
('Rogers'),
('Emirates'),
('Claro'),
('Danaher'),
('The North Face'),
('Express Scripts'),
('ANZ'),
('Daikin'),
('Texas Instruments'),
('Conch'),
('Ross Dress For Less'),
('OCBC Bank'),
('Tide'),
('BD'),
('Geely'),
('AIG'),
('Haidilao'),
('BUICK'),
('Sprite'),
('Bloomberg'),
('New China Life (NCL)'),
('Saint-Gobain'),
('Bayer'),
('McLane'),
('SiriusXM'),
('Cardinal Health'),
('Marshalls'),
('BOE'),
('Electronic Arts'),
('Telia'),
('Indian Oil'),
('BNY Mellon'),
('AmerisourceBergen'),
('Aflac'),
('Safran'),
('LENNAR'),
('Servicenow'),
('Wipro'),
('GS Group'),
('Blackrock'),
('McCain'),
('Sodexo'),
('Yonghui Superstores'),
('CNP Assurances'),
('China Re'),
('Cadillac'),
('China Taiping'),
('Anta'),
('Logan'),
('Emerson Electric'),
('Gatorade'),
('Victoria\'s Secret'),
('La Poste'),
('Bristol-Myers Squibb'),
('Sainsbury\'s'),
('BDO Global'),
('Merck &amp; Co'),
('ASML'),
('Nordea'),
('Garnier'),
('Canadian National Railway'),
('Huggies'),
('D.R. Horton'),
('Fujitsu Group'),
('Abbott'),
('Tim Hortons'),
('Maersk'),
('Gujing Gong Jiu'),
('HBO'),
('Bank of Beijing'),
('Cummins'),
('Omega'),
('Banco do Brasil'),
('Victoria'),
('Pfizer'),
('SABIC'),
('Head &amp; Shoulders'),
('Sompo Japan Nipponkoa'),
('UOB'),
('Edeka'),
('MSCI');

INSERT INTO `mercado_liebre_entregable`.`products` (`title`, `description`, `photo`, `price`, `stock`, `brand_id`, `category_id`, `created_at`) VALUES ('Notebook Cx Intel Atom 4gb Ram 64gb Ssd Full Hd 1080p Win 10', 'Producto: Notebook CX 23500w\n\n¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\n\nCaracterísticas del producto\n• Con Windows 10 - Home y todo el poder de Intel\n• Incluye: Cargador de pared, Manual de usuario y tarjeta de garantía.\nEspecificaciones principales\n• Pantalla: 14.1” – Formato 16:9 - LED/IPS\n• Procesador: Intel Atom x5-Z8350 1.44Ghz\n• Memoria RAM: 4GB DDR3\n• Almacenamiento: 64GB eMMC\n• Gráficos: Intel ®HD Graphics\n• Resolución: 1920 px x 1080 px - FullHD\n• Cámarafrontal: 0.3MP\n• Teclado: Español\n• Batería: Lithium – ion polymer battery 3.7V 9000 mAh\n• Puertos: Mini HDMI Type C 1.4 / x1USB3.0 / x1USB2.0 SoportaSDHC / SDXC\n• Conectividad: WIFI802.11 b/g/n – Bluetooth 4.0\n• Sistema operativo: Windows 10 Home\n• Dimensiones: 328mm x 220mm x 17.8mm\n• Peso: 1.15 kg\n• Color disponible: Blanco\n• Garantía: 12meses\n\n', '/images/products/img-laptop-lenovo.jpg', '31299', '15', '373', '144', '2020-03-13 14:36:00');
